name: Frontend CI/CD

on:
  push:
    branches:
      - feature/CICD
  pull_request:
    branches:
      - feature/CICD

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22' # Use the appropriate Node.js version
        
    - name: Deleting installation files
      working-directory: ./Curota # Adjust the path to your frontend folder
      #run: npm install
      run: rm -rf node_modules

    - name: Install dependencies
      working-directory: ./Curota # Adjust the path to your frontend folder
      run: npm install
        
      #run: npm install --save-dev jest @testing-library/react @testing-library/jest-dom
      
    - name: Install react-router
      working-directory: ./Curota # Adjust the path to your frontend folder
      run: npm install react-router-dom@7

#    - name: Run tests
#      working-directory: ./Curota
#      run: npm test
      
    - name: Build
      working-directory: ./Curota
      run: yarn build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: build-artifacts
        path: ./Curota/build

  Deploy:
    runs-on: ubuntu-latestls
    needs: Build
        
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        
    - name: Deploy
      run: |
        cd build
        ls
        echo "Add deployment commands here" # Replace with your deployment steps
